{% set name = "access" %}
{% set version = "1.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89d0043e3596854701b72c77dfedb677839a5b416a18362c222b7d321ad02138

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - geopandas
    - numpy >=1.3
    - pandas >=0.23.4
    - python >=3.7
    - requests >=2

test:
  imports:
    - access
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://access.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: classical and novel measures of spatial accessibility to services

  description: |
    access is a class and function for calculating the spatial accessibility
    of resources.  It is designed for python 3.7 and higher.
    Pandas (and numpy) are required, and geopandas allows for some additional functionality.
  doc_url: https://pysal.org/access/
  dev_url: https://github.com/pysal/access

extra:
  recipe-maintainers:
    - ocefpaf
    - JamesSaxon
    - jkoschinsky
    - martinfleis
    - knaaptime
    - jGaboardi
