{% set name = "access" %}
{% set version = "1.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22fcc61b5bdb4ddc64378e7906ba7cee53d4221041ecc625ebd1dfd1348be5d2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - geopandas
    - numpy >=1.3
    - pandas >=0.23.4
    - python >={{ python_min }}
    - requests >=2

test:
  imports:
    - access
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://access.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: classical and novel measures of spatial accessibility to services

  description: |
    access is a class and function for calculating the spatial accessibility
    of resources.  It is designed for python 3.7 and higher.
    Pandas (and numpy) are required, and geopandas allows for some additional functionality.
  doc_url: https://pysal.org/access/
  dev_url: https://github.com/pysal/access

extra:
  recipe-maintainers:
    - ocefpaf
    - JamesSaxon
    - jkoschinsky
    - martinfleis
    - knaaptime
    - jGaboardi
