{% set name = "access" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8516a834a45538292640bb25c96ffab0db80545dcc5303fbdc199670c6d96e8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - scipy >=0.11
    - numpy >=1.3
    - pandas >=0.23.4
    - requests >=2

test:
  # Other tests run through CI.
  imports:
    - access

about:
  home: https://access.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: classical and novel measures of spatial accessibility to services

  description: |
    access is a class and function for calculating the spatial accessibility
    of resources.  It is designed for python 3.5 and higher.
    Pandas (and numpy) are required, and geopandas allows for some additional functionality.
  doc_url: https://access.readthedocs.io/
  dev_url: https://github.com/pysal/access

extra:
  recipe-maintainers:
    - JamesSaxon
    - jkoschinsky
